name: Deploy Vercel

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [custom_event_type, wordpress]
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Setup project Node 14
        uses: actions/setup-node@v2
        with:
          node-version: v14.17.6

      - name: Prepare project environment
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          WORDPRESS_API_URL: ${{ secrets.WORDPRESS_API_URL}}
          SENDGRID_API_KEY: ${{ secrets.NEXT_PUBLIC_SENDGRID_API_KEY }}
          S3_UPLOAD_KEY: ${{ secrets.NEXT_PUBLIC_S3_UPLOAD_KEY }}
          S3_UPLOAD_SECRET: ${{ secrets.NEXT_PUBLIC_S3_UPLOAD_SECRET }}
          S3_UPLOAD_BUCKET: ${{ secrets.NEXT_PUBLIC_S3_UPLOAD_BUCKET }}
          S3_UPLOAD_REGION: ${{ secrets.NEXT_PUBLIC_S3_UPLOAD_REGION }}
          RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
          GOOGLE_MAP_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAP_KEY }}

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          #github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} #Required
          github-comment: false
          vercel-args: '--prod' #Optional
